### ISSUE TITLE
the mod outputs errors but it works fine,

### ISSUE THREAD

**Issue by SpikeTheDragon03** [ZioPao/The-Only-Cure#117]
**Describe the bug**
the mods works fine but i keep getting errors for this mod but the error log says something about brutal handwork wich i dont understand how to fix, iv tried to re order the mods 
iv tried to re download them and to delet all my mods and re download them piece by piece but nothing works , iv tried to jst launch the only cure mod and its dependencies but stilll errors nonstop

**To Reproduce**

**Logs**
`attempted index: isZombie of non-table: zombie.iso.objects.IsoFallingClothing@66fbaa30
function: addToHitList -- file: BrutalAttack.lua line # 511 | MOD: Brutal Handwork
function: FindAndAttackTargets -- file: BrutalAttack.lua line # 583 | MOD: Brutal Handwork
function: animEvent -- file: BH_MeleeAttackTimedAction.lua line # 87 | MOD: Brutal Handwork
java.lang.RuntimeException: attempted index: isZombie of non-table: zombie.iso.objects.IsoFallingClothing@66fbaa30
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1861)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:48)
    at zombie.characters.CharacterTimedActions.LuaTimedActionNew.OnAnimEvent(LuaTimedActionNew.java:152)
    at zombie.characters.IsoPlayer.OnAnimEvent(IsoPlayer.java:9409)
    at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator.OnAnimEvent(AdvancedAnimator.java:264)
    at zombie.core.skinnedmodel.advancedanimation.AnimLayer.invokeAnimEvent(AnimLayer.java:211)
    at zombie.core.skinnedmodel.advancedanimation.AnimLayer.updateInternal(AnimLayer.java:419)
    at zombie.GameProfiler.invokeAndMeasure(GameProfiler.java:166)
    at zombie.core.skinnedmodel.advancedanimation.AnimLayer.Update(AnimLayer.java:323)
    at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator$SubLayerSlot.update(AdvancedAnimator.java:665)
    at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator.updateInternal(AdvancedAnimator.java:403)
    at zombie.GameProfiler.invokeAndMeasure(GameProfiler.java:166)
    at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator.update(AdvancedAnimator.java:368)
    at zombie.characters.IsoGameCharacter.postUpdateInternal(IsoGameCharacter.java:12087)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.characters.IsoGameCharacter.postupdate(IsoGameCharacter.java:12063)
    at zombie.characters.IsoPlayer.postupdateInternal(IsoPlayer.java:3740)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.characters.IsoPlayer.postupdate(IsoPlayer.java:3733)
    at zombie.MovingObjectUpdateSchedulerUpdateBucket.postupdate(MovingObjectUpdateSchedulerUpdateBucket.java:97)
    at zombie.MovingObjectUpdateScheduler.postupdate(MovingObjectUpdateScheduler.java:168)
    at zombie.CollisionManager.resolveContactsInternal(CollisionManager.java:411)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.CollisionManager.ResolveContacts(CollisionManager.java:236)
    at zombie.iso.IsoWorld.updateInternal(IsoWorld.java:3502)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.iso.IsoWorld.update(IsoWorld.java:3427)
    at zombie.gameStates.IngameState.updateInternal(IngameState.java:1617)
    at zombie.gameStates.IngameState.update(IngameState.java:1333)
    at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
    at zombie.GameWindow.logic(GameWindow.java:298)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

`attempted index: isZombie of non-table: zombie.iso.objects.IsoFallingClothing@66fbaa30
function: addToHitList -- file: BrutalAttack.lua line # 511 | MOD: Brutal Handwork
function: FindAndAttackTargets -- file: BrutalAttack.lua line # 583 | MOD: Brutal Handwork
function: animEvent -- file: BH_MeleeAttackTimedAction.lua line # 87 | MOD: Brutal Handwork
java.lang.RuntimeException: attempted index: isZombie of non-table: zombie.iso.objects.IsoFallingClothing@66fbaa30
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1861)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:48)
    at zombie.characters.CharacterTimedActions.LuaTimedActionNew.OnAnimEvent(LuaTimedActionNew.java:152)
    at zombie.characters.IsoPlayer.OnAnimEvent(IsoPlayer.java:9409)
    at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator.OnAnimEvent(AdvancedAnimator.java:264)
    at zombie.core.skinnedmodel.advancedanimation.AnimLayer.invokeAnimEvent(AnimLayer.java:211)
    at zombie.core.skinnedmodel.advancedanimation.AnimLayer.updateInternal(AnimLayer.java:419)
    at zombie.GameProfiler.invokeAndMeasure(GameProfiler.java:166)
    at zombie.core.skinnedmodel.advancedanimation.AnimLayer.Update(AnimLayer.java:323)
    at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator$SubLayerSlot.update(AdvancedAnimator.java:665)
    at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator.updateInternal(AdvancedAnimator.java:403)
    at zombie.GameProfiler.invokeAndMeasure(GameProfiler.java:166)
    at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator.update(AdvancedAnimator.java:368)
    at zombie.characters.IsoGameCharacter.postUpdateInternal(IsoGameCharacter.java:12087)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.characters.IsoGameCharacter.postupdate(IsoGameCharacter.java:12063)
    at zombie.characters.IsoPlayer.postupdateInternal(IsoPlayer.java:3740)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.characters.IsoPlayer.postupdate(IsoPlayer.java:3733)
    at zombie.MovingObjectUpdateSchedulerUpdateBucket.postupdate(MovingObjectUpdateSchedulerUpdateBucket.java:97)
    at zombie.MovingObjectUpdateScheduler.postupdate(MovingObjectUpdateScheduler.java:168)
    at zombie.CollisionManager.resolveContactsInternal(CollisionManager.java:411)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.CollisionManager.ResolveContacts(CollisionManager.java:236)
    at zombie.iso.IsoWorld.updateInternal(IsoWorld.java:3502)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.iso.IsoWorld.update(IsoWorld.java:3427)
    at zombie.gameStates.IngameState.updateInternal(IngameState.java:1617)
    at zombie.gameStates.IngameState.update(IngameState.java:1333)
    at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
    at zombie.GameWindow.logic(GameWindow.java:298)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`
**Additional context**
iv never like mentioned anything to mod creators before so sorry if its sloppy

**Comment by ZioPao** [comment]
> Fancy and Brutal are broken-ish and possibly abandoned mods, I recommend not using them.

the author never finished the updated version, and Brutal is basically integral to TOC. What issues are there in particular? I may be able to get in contact with dhert and figure out something.

**Comment by m-hynek** [comment]
> > Fancy and Brutal are broken-ish and possibly abandoned mods, I recommend not using them.
> 
> the author never finished the updated version, and Brutal is basically integral to TOC. What issues are there in particular? I may be able to get in contact with dhert and figure out something.

well for Brutal, when dualweilding, offhand attack does nothing for most of the time, it just triggers zombie hit animation without damage and throwing occasional errors. I can't recall if it was same when weilding offhand only

and Fancy has some sync issues and breaking animations of other mods, like playing Lifestyle instruments. Update from below screen never released

![image](https://github.com/user-attachments/assets/eb65d221-7c11-45f1-8f0d-dbedf9530bce)

**Comment by 4nalMac** [comment]
> > > Fancy and Brutal are broken-ish and possibly abandoned mods, I recommend not using them.
> > 
> > 
> > the author never finished the updated version, and Brutal is basically integral to TOC. What issues are there in particular? I may be able to get in contact with dhert and figure out something.
> 
> well for Brutal, when dualweilding, offhand attack does nothing for most of the time, it just triggers zombie hit animation without damage and throwing occasional errors. I can't recall if it was same when weilding offhand only
> 
> and Fancy has some sync issues and breaking animations of other mods, like playing Lifestyle instruments. Update from below screen never released
> 
> ![image](https://private-user-images.githubusercontent.com/44279396/359314822-eb65d221-7c11-45f1-8f0d-dbedf9530bce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTY0MzksIm5iZiI6MTcyNDE1NjEzOSwicGF0aCI6Ii80NDI3OTM5Ni8zNTkzMTQ4MjItZWI2NWQyMjEtN2MxMS00NWYxLThmMGQtZGJlZGY5NTMwYmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDEyMTUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMWZhYzVmOTU5NzUwYzAyN2FmYWFiYzEyOTI5ZGU5MGZhY2UyZTJiY2VhZmFkYjNjYWI3OGViNjZjYzc2OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cCaOODULdcA90y6u9SSYPzZjEAIllmtLs-u5IGVryoI)

I don't have many issues with combat using brutal besides it sometimes hitting the zombie behind the one I want to attack, in fact I find that damage is higher than when I fight right handed. I can cleave through hoards. that being said I have noticed items like gas cannisters getting stuck in my offhand but I doubt that is related to TOC in any way but maybe since my surivor is wearing a prosthetic.

on an unrelated note I wonder what happened to dhert. I use pretty much all their mods so it's a bit upsetting they haven't received any updates. Hope they're alright and just waiting on b42.

**Comment by m-hynek** [comment]
> > > > Fancy and Brutal are broken-ish and possibly abandoned mods, I recommend not using them.
> > > 
> > > 
> > > the author never finished the updated version, and Brutal is basically integral to TOC. What issues are there in particular? I may be able to get in contact with dhert and figure out something.
> > 
> > 
> > well for Brutal, when dualweilding, offhand attack does nothing for most of the time, it just triggers zombie hit animation without damage and throwing occasional errors. I can't recall if it was same when weilding offhand only
> > and Fancy has some sync issues and breaking animations of other mods, like playing Lifestyle instruments. Update from below screen never released
> > ![image](https://private-user-images.githubusercontent.com/44279396/359314822-eb65d221-7c11-45f1-8f0d-dbedf9530bce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTY0MzksIm5iZiI6MTcyNDE1NjEzOSwicGF0aCI6Ii80NDI3OTM5Ni8zNTkzMTQ4MjItZWI2NWQyMjEtN2MxMS00NWYxLThmMGQtZGJlZGY5NTMwYmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDEyMTUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMWZhYzVmOTU5NzUwYzAyN2FmYWFiYzEyOTI5ZGU5MGZhY2UyZTJiY2VhZmFkYjNjYWI3OGViNjZjYzc2OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cCaOODULdcA90y6u9SSYPzZjEAIllmtLs-u5IGVryoI)
> 
> I don't have many issues with combat using brutal besides it sometimes hitting the zombie behind the one I want to attack, in fact I find that damage is higher than when I fight right handed. I can cleave through hoards. that being said I have noticed items like gas cannisters getting stuck in my offhand but I doubt that is related to TOC in any way but maybe since my surivor is wearing a prosthetic.
> 
> on an unrelated note I wonder what happened to dhert. I use pretty much all their mods so it's a bit upsetting they haven't received any updates. Hope they're alright and just waiting on b42.

im talking about multiplayer

**Comment by SpikeTheDragon03** [comment]
> > Fancy and Brutal are broken-ish and possibly abandoned mods, I recommend not using them.
> 
> the author never finished the updated version, and Brutal is basically integral to TOC. What issues are there in particular? I may be able to get in contact with dhert and figure out something.

the issue is just that i get errors when using the mod s  and and im alittle worried to remove any more mods bc the only cure steam page says i should use both fancy and brutal for the intended exerience .

should i just remove them and try to run it without it

**Comment by 4nalMac** [comment]
> > > > > Fancy and Brutal are broken-ish and possibly abandoned mods, I recommend not using them.
> > > > 
> > > > 
> > > > the author never finished the updated version, and Brutal is basically integral to TOC. What issues are there in particular? I may be able to get in contact with dhert and figure out something.
> > > 
> > > 
> > > well for Brutal, when dualweilding, offhand attack does nothing for most of the time, it just triggers zombie hit animation without damage and throwing occasional errors. I can't recall if it was same when weilding offhand only
> > > and Fancy has some sync issues and breaking animations of other mods, like playing Lifestyle instruments. Update from below screen never released
> > > ![image](https://private-user-images.githubusercontent.com/44279396/359314822-eb65d221-7c11-45f1-8f0d-dbedf9530bce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTY0MzksIm5iZiI6MTcyNDE1NjEzOSwicGF0aCI6Ii80NDI3OTM5Ni8zNTkzMTQ4MjItZWI2NWQyMjEtN2MxMS00NWYxLThmMGQtZGJlZGY5NTMwYmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDEyMTUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMWZhYzVmOTU5NzUwYzAyN2FmYWFiYzEyOTI5ZGU5MGZhY2UyZTJiY2VhZmFkYjNjYWI3OGViNjZjYzc2OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cCaOODULdcA90y6u9SSYPzZjEAIllmtLs-u5IGVryoI)
> > 
> > 
> > I don't have many issues with combat using brutal besides it sometimes hitting the zombie behind the one I want to attack, in fact I find that damage is higher than when I fight right handed. I can cleave through hoards. that being said I have noticed items like gas cannisters getting stuck in my offhand but I doubt that is related to TOC in any way but maybe since my surivor is wearing a prosthetic.
> > on an unrelated note I wonder what happened to dhert. I use pretty much all their mods so it's a bit upsetting they haven't received any updates. Hope they're alright and just waiting on b42.
> 
> im talking about multiplayer

So was I. I've been playing on a server and have had no issue with offhand combat minus what I mentioned. Not saying you are wrong since I don't have any health bar mod to actually check if each hit is doing damage but It certainly feels like it with how easily I can mop up zeds.

**Comment by SpikeTheDragon03** [comment]
> > Fancy and Brutal are broken-ish and possibly abandoned mods, I recommend not using them.
> 
> the author never finished the updated version, and Brutal is basically integral to TOC. What issues are there in particular? I may be able to get in contact with dhert and figure out something.

im alittle unsure what the issue is like the combat works fine with dualvielding , but evrey like 20th zombie kill i get th errors i posted in tmy original post , amputation works fine aswll, i also had some issue where my character wont push

**Comment by ZioPao** [comment]
> > > Fancy and Brutal are broken-ish and possibly abandoned mods, I recommend not using them.
> > 
> > 
> > the author never finished the updated version, and Brutal is basically integral to TOC. What issues are there in particular? I may be able to get in contact with dhert and figure out something.
> 
> im alittle unsure what the issue is like the combat works fine with dualvielding , but evrey like 20th zombie kill i get th errors i posted in tmy original post , amputation works fine aswll, i also had some issue where my character wont push

Disabling Brutal and Fancy shouldn't cause any issues with TOC, but if the only issue here is just an output of errors, I wouldn't worry too much.

I've talked with dhert a few months ago, he's been waiting for B42 but as you may know, it doesn't look like it's coming out too soon.

**Comment by SpikeTheDragon03** [comment]
Okay il try it without them then see how it goes, thank you. Sorry if I was missing some information I don't really know what information would be needed
