### ISSUE TITLE
Everything just broken

### ISSUE THREAD

**Issue by shlpmate** [ZioPao/The-Only-Cure#29]
we play 4 player co-op, in the bottom left we get spammed with error messages counting from 0 to like a million at high speed, and most actions dont work, I saw you fixed the clothes and i thought that was the only problem but like crafting and equipping weapons.

**Comment by shlpmate** [comment]
this was one of the error message that i happened to choose but it was before teh bugfix for clothes, but idk might help




`attempted index: Hand_R of non-table: null
function: getIsCut -- file: DataController.lua line # 224 | MOD: The Only Cure
function: CalculateAmputatedLimbs -- file: CachedDataHandler.lua line # 47 | MOD: The Only Cure
function: CalculateHighestAmputatedLimbs -- file: CachedDataHandler.lua line # 88 | MOD: The Only Cure
function: CalculateCacheableValues -- file: CachedDataHandler.lua line # 24 | MOD: The Only Cure
Callframe at: se.krka.kahlua.integration.expose.MultiLuaJavaInvoker@83df6185
function: ReceiveData -- file: DataController.lua line # 404 | MOD: The Only Cure
java.lang.RuntimeException: attempted index: Hand_R of non-table: null
at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:92)
    at zombie.Lua.LuaEventManager.triggerEventGarbage(LuaEventManager.java:103)
    at zombie.Lua.LuaManager$GlobalObject.triggerEvent(LuaManager.java:3068)
    at jdk.internal.reflect.GeneratedMethodAccessor428.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:62)
    at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:198)
    at se.krka.kahlua.integration.expose.MultiLuaJavaInvoker.call(MultiLuaJavaInvoker.java:60)
    at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:134)
    at zombie.world.moddata.GlobalModData.receive(GlobalModData.java:167)
    at zombie.network.GameClient.receiveGlobalModData(GameClient.java:6116)
    at zombie.network.PacketTypes$PacketType.onMainLoopHandlePacketInternal(PacketTypes.java:1028)
    at zombie.network.GameClient.mainLoopHandlePacketInternal(GameClient.java:644)
    at zombie.network.GameClient.mainLoopDealWithNetData(GameClient.java:621)
    at zombie.network.GameClient.update(GameClient.java:431)
    at zombie.GameWindow.logic(GameWindow.java:232)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:667)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)

**Comment by ZioPao** [comment]
Hi, by co-op what are we talking about? Hosted game from within the game or split screen?

**Comment by shlpmate** [comment]
Im using coop so i host server and they join on their own pc with their own copy of the game.

**Comment by ZioPao** [comment]
> Im using coop so i host server and they join on their own pc with their own copy of the game.

Alright. Were you running the older version of the mod by any chance?

**Comment by Kvamstrams** [comment]
Currently getting the same error aswell. Hosting a dedicated server. Had the older version of the mod before.
Does the server have to be wiped in order for the mod to be working?

**Comment by ZioPao** [comment]
> Currently getting the same error aswell. Hosting a dedicated server. Had the older version of the mod before. Does the server have to be wiped in order for the mod to be working?

If you swapped the old version with the Rebuilt version, then yeah, things could go haywire. A full on wipe shouldn't be necessary, but there could be issues with pre-existing characters. Also the new items wouldn't spawn on an already generated world.

**Comment by shlpmate** [comment]
No, i remade the world and made sure i got rid of old cure but still errore

**Comment by ZioPao** [comment]
> No, i remade the world and made sure i got rid of old cure but still errore

I may need the full logs from one of your players. Server logs would be helpful too. If you can provide them, that would help a ton.

**Comment by shlpmate** [comment]
I can’t get it right now but if you can tell me how, all i know now is that you fixed the clothes problems, i can’t do most actions and that the error code just counts up infinitely.

**Comment by Kvamstrams** [comment]
> I can’t get it right now but if you can tell me how, all i know now is that you fixed the clothes problems, i can’t do most actions and that the error code just counts up infinitely.

Same for me aswell. I can provide the files tomorrow.

**Comment by ZioPao** [comment]
> I can’t get it right now but if you can tell me how, all i know now is that you fixed the clothes problems, i can’t do most actions and that the error code just counts up infinitely.

`C:\Users\YOUR_NAME\Zomboid\console.txt`

**Comment by Anwonn** [comment]
`attempted index: Hand_L of non-table: null
function: getIsCut -- file: DataController.lua line # 224 | MOD: The Only Cure
function: getDamagedParts -- file: HealthPanel.lua line # 272 | MOD: The Only Cure
function: updateBodyPartList -- file: ISHealthPanel.lua line # 526 | Vanilla
function: update -- file: ISHealthPanel.lua line # 396 | Vanilla
function: update -- file: HealthPanel.lua line # 133 | MOD: The Only Cure
java.lang.RuntimeException: attempted index: Hand_L of non-table: null
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1827)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:38)
    at zombie.ui.UIElement.update(UIElement.java:1589)
    at zombie.ui.UIElement.update(UIElement.java:1606)
    at zombie.ui.UIElement.update(UIElement.java:1606)
    at zombie.ui.UIManager.update(UIManager.java:1042)
    at zombie.GameWindow.logic(GameWindow.java:262)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

**Comment by Anwonn** [comment]
> > I can’t get it right now but if you can tell me how, all i know now is that you fixed the clothes problems, i can’t do most actions and that the error code just counts up infinitely.
> 
> `C:\Users\YOUR_NAME\Zomboid\console.txt`

[Uploading console.txt…]()

**Comment by Anwonn** [comment]
> > I can’t get it right now but if you can tell me how, all i know now is that you fixed the clothes problems, i can’t do most actions and that the error code just counts up infinitely.
> 
> `C:\Users\YOUR_NAME\Zomboid\console.txt`

[console.txt](https://github.com/ZioPao/The-Only-Cure/files/15206504/console.txt)

**Comment by shlpmate** [comment]
[console.txt](https://github.com/ZioPao/The-Only-Cure/files/15209307/console.txt)

**Comment by ZioPao** [comment]
I pushed an update with some fixes. let me know if anything changes.

**Comment by Anwonn** [comment]
nothing change, the mod still with error ;-;

**Comment by ZioPao** [comment]
> nothing change, the mod still with error ;-;

Same errors? Can you post the new logs?

**Comment by Anwonn** [comment]
> > nothing change, the mod still with error ;-;
> 
> Same errors? Can you post the new logs?

[console.txt](https://github.com/ZioPao/The-Only-Cure/files/15214002/console.txt)

**Comment by theultimateshape** [comment]
lol i had the same error a bit ago, do you have a respawn mod perhaps? or na

**Comment by theultimateshape** [comment]
the error in particular:
WARN : General     , 1714877135424> 0> TraitFactory$Trait.addXPBoost> invalid perk passed to Trait.addXPBoost trait=Amputated Left Hand perk=null
WARN : General     , 1714877135425> 0> TraitFactory$Trait.addXPBoost> invalid perk passed to Trait.addXPBoost trait=Amputated Left Forearm perk=null
WARN : General     , 1714877135425> 0> TraitFactory$Trait.addXPBoost> invalid perk passed to Trait.addXPBoost trait=Amputated Left Upper arm perk=null

**Comment by theultimateshape** [comment]
> nothing change, the mod still with error ;-;

i believe it fucks your save, i soft reset my server and it was still like that

**Comment by Nox-Matt** [comment]
I do get the same problem as well, The error happend when you die, when you make a new characters, you can't do anything, equip item, clothes, etc. I think with this mod enabled, the game think you amputated both of your arms or limbs to be exact, that's why the error log tells you the value for Hand_R or Hand_L, is null, here is my error logs:

`attempted index: Hand_L of non-table: null
function: getIsCut -- file: DataController.lua line # 232 | MOD: The Only Cure
function: getDamagedParts -- file: HealthPanel.lua line # 272 | MOD: The Only Cure
function: updateBodyPartList -- file: ISHealthPanel.lua line # 526 | Vanilla
function: update -- file: ISHealthPanel.lua line # 396 | Vanilla
function: update -- file: HealthPanel.lua line # 133 | MOD: The Only Cure
java.lang.RuntimeException: attempted index: Hand_L of non-table: null
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1827)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:38)
    at zombie.ui.UIElement.update(UIElement.java:1589)
    at zombie.ui.UIElement.update(UIElement.java:1606)
    at zombie.ui.UIElement.update(UIElement.java:1606)
    at zombie.ui.UIManager.update(UIManager.java:1042)
    at zombie.GameWindow.logic(GameWindow.java:262)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)


Overlapping the Only-Cure Health Interface with Vanilla i think

**Comment by ZioPao** [comment]
> I do get the same problem as well, The error happend when you die, when you make a new characters, you can't do anything, equip item, clothes, etc. I think with this mod enabled, the game think you amputated both of your arms or limbs to be exact, that's why the error log tells you the value for Hand_R or Hand_L, is null, here is my error logs:
> 
> `attempted index: Hand_L of non-table: null function: getIsCut -- file: DataController.lua line # 232 | MOD: The Only Cure function: getDamagedParts -- file: HealthPanel.lua line # 272 | MOD: The Only Cure function: updateBodyPartList -- file: ISHealthPanel.lua line # 526 | Vanilla function: update -- file: ISHealthPanel.lua line # 396 | Vanilla function: update -- file: HealthPanel.lua line # 133 | MOD: The Only Cure java.lang.RuntimeException: attempted index: Hand_L of non-table: null at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689) at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492) at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163) at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980) at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1827) at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:38) at zombie.ui.UIElement.update(UIElement.java:1589) at zombie.ui.UIElement.update(UIElement.java:1606) at zombie.ui.UIElement.update(UIElement.java:1606) at zombie.ui.UIManager.update(UIManager.java:1042) at zombie.GameWindow.logic(GameWindow.java:262) at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71) at zombie.GameWindow.frameStep(GameWindow.java:765) at zombie.GameWindow.run_ez(GameWindow.java:681) at zombie.GameWindow.mainThread(GameWindow.java:495) at java.base/java.lang.Thread.run(Unknown Source)
> 
> Overlapping the Only-Cure Health Interface with Vanilla i think

I need the full logs, only snippets aren't really helpful to pinpoint the issue.

**Comment by ZioPao** [comment]
This issue has become just a big mess, I'm gonna close this, since I just pushed an update that should fix the issue @Nox-Matt reported.

For any new errors, please open new issues.
