### ISSUE TITLE
Errors during fist punch

### ISSUE THREAD

**Issue by ChaoZavitkar** [ZioPao/The-Only-Cure#66]
I am using Fancy and Brutal Handwork and every time I punch into the air with prosthetics (I didn't try to fight with zombies) I get an error.

**To Reproduce**
1. Amputate arm
2. Equip the prosthetic (tried with arm)
3. Attack with Brutal Handwork with "Always raise fists when unarmed", "Enable Unarmed Attacks" and "Automatically left and right attacks when dual-wielding melee weapons" enabled in the config

**Logs**
`function: FindAndAttackTargets -- file: BrutalAttack.lua line # 621 | MOD: Brutal Handwork
function: animEvent -- file: BH_MeleeAttackTimedAction.lua line # 87 | MOD: Brutal Handwork
java.lang.RuntimeException: Object tried to call nil in FindAndAttackTargets
    at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:973)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1861)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:48)
    at zombie.characters.CharacterTimedActions.LuaTimedActionNew.OnAnimEvent(LuaTimedActionNew.java:152)
    at zombie.characters.IsoPlayer.OnAnimEvent(IsoPlayer.java:9409)
    at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator.OnAnimEvent(AdvancedAnimator.java:264)
    at zombie.core.skinnedmodel.advancedanimation.AnimLayer.invokeAnimEvent(AnimLayer.java:211)
    at zombie.core.skinnedmodel.advancedanimation.AnimLayer.updateInternal(AnimLayer.java:419)
    at zombie.GameProfiler.invokeAndMeasure(GameProfiler.java:166)
    at zombie.core.skinnedmodel.advancedanimation.AnimLayer.Update(AnimLayer.java:323)
    at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator$SubLayerSlot.update(AdvancedAnimator.java:665)
    at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator.updateInternal(AdvancedAnimator.java:403)
    at zombie.GameProfiler.invokeAndMeasure(GameProfiler.java:166)
    at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator.update(AdvancedAnimator.java:368)
    at zombie.characters.IsoGameCharacter.postUpdateInternal(IsoGameCharacter.java:12087)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.characters.IsoGameCharacter.postupdate(IsoGameCharacter.java:12063)
    at zombie.characters.IsoPlayer.postupdateInternal(IsoPlayer.java:3740)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.characters.IsoPlayer.postupdate(IsoPlayer.java:3733)
    at zombie.MovingObjectUpdateSchedulerUpdateBucket.postupdate(MovingObjectUpdateSchedulerUpdateBucket.java:97)
    at zombie.MovingObjectUpdateScheduler.postupdate(MovingObjectUpdateScheduler.java:168)
    at zombie.CollisionManager.resolveContactsInternal(CollisionManager.java:411)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.CollisionManager.ResolveContacts(CollisionManager.java:236)
    at zombie.iso.IsoWorld.updateInternal(IsoWorld.java:3502)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.iso.IsoWorld.update(IsoWorld.java:3427)
    at zombie.gameStates.IngameState.updateInternal(IngameState.java:1617)
    at zombie.gameStates.IngameState.update(IngameState.java:1333)
    at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
    at zombie.GameWindow.logic(GameWindow.java:298)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

**Additional context**
Attacking with weapons is fine I think, I didn't see any errors during fighting with weapons

**Comment by ZioPao** [comment]
Nice catch. Yeah, it's something that should be addressed directly into Brutal Handwork, I'll see if I can think of some kind of fix from my side

**Comment by criticap** [comment]
The errors come when you attack with an item that isn't consider as weapon or clothing category.
For example, holding a paper on your hand and you punch, error appear.
I think the solution can be as easy as changing the item category of Prosthetic arm.
