### ISSUE TITLE
Error when i have suture needle in my inventory

### ISSUE THREAD

**Issue by AbyFwz** [ZioPao/The-Only-Cure#85]
**Describe the bug**
I have an error when i open the context menu on saw item when i have suture needle in my inventory

**To Reproduce**
1. Have 1 saw, 1 suture needle holder, and 1 suture needle
2. Go to 'Inventory'
3. Click on 'Saw'
4. Error appeared

**Logs**
Please upload your game logs too. Server logs are useful too.
`function: GetStitchesConsumableItem -- file: CutLimbInteractionHandler.lua line # 43 | MOD: The Only Cure
function: AddInventoryAmputationMenu -- file: CutLimbInteractionHandler.lua line # 172 | MOD: The Only Cure
Callframe at: se.krka.kahlua.integration.expose.MultiLuaJavaInvoker@88f9a99b
function: createMenu -- file: ISInventoryPaneContextMenu.lua line # 787 | Vanilla
function: executePatchedCode -- file: PatchUtil.lua line # 5 | MOD: Susceptible
function: onRightMouseUp -- file: ISInventoryPane.lua line # 1444 | Vanilla
java.lang.RuntimeException: Object tried to call nil in GetStitchesConsumableItem
    at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:973)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:173)
    at zombie.Lua.LuaEventManager.triggerEventGarbage(LuaEventManager.java:186)
    at zombie.Lua.LuaManager$GlobalObject.triggerEvent(LuaManager.java:3080)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:62)
    at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:198)
    at se.krka.kahlua.integration.expose.MultiLuaJavaInvoker.call(MultiLuaJavaInvoker.java:60)
    at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallBoolean(KahluaThread.java:1924)
    at se.krka.kahlua.integration.LuaCaller.protectedCallBoolean(LuaCaller.java:104)
    at zombie.ui.UIElement.onRightMouseUp(UIElement.java:1458)
    at zombie.ui.UIElement.onRightMouseUp(UIElement.java:1416)
    at zombie.ui.UIManager.update(UIManager.java:910)
    at zombie.GameWindow.logic(GameWindow.java:262)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:667)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`
![PZ TOC Suture Needle Error](https://github.com/ZioPao/The-Only-Cure/assets/13820551/f4d9b93e-694f-4f6a-80a5-2d5aa2e96867)

**Additional context**
I instal TOC with Susceptible and susceptible overhaul mods

**Comment by ZioPao** [comment]
Noted, will be fixed in the next version.

**Comment by ZioPao** [comment]
Resolved in v2.0.15
