### ISSUE TITLE
I can't create a MP server with the mod in the workshop

### ISSUE THREAD

**Issue by Baklazan-guy** [ZioPao/The-Only-Cure#87]
When i try to put the mod in the workshop and start up the multiplayer it tells me "Server has stoppped during launched (NormalTermination"). I don't know if this is a bug or im doing somerthing wrong but any help would be appreciated

here is the server log i think 
[15-06-24 19:15:17.734] ERROR: General , 1718471717734> java.nio.file.NoSuchFileException: /lua/AshenMPRanking/servertest.
[15-06-24 19:15:17.735] ERROR: General , 1718471717735> at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.deleteFile(Unknown Source).
[15-06-24 19:15:17.735] ERROR: General , 1718471717735> at jdk.zipfs/jdk.nio.zipfs.ZipPath.delete(Unknown Source).
[15-06-24 19:15:17.735] ERROR: General , 1718471717735> at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.delete(Unknown Source).
[15-06-24 19:15:17.735] ERROR: General , 1718471717735> at java.base/java.nio.file.Files.delete(Unknown Source).
[15-06-24 19:15:17.735] ERROR: General , 1718471717735> at zombie.core.logger.ZipLogs.deleteDirectory(ZipLogs.java:305).
[15-06-24 19:15:17.735] ERROR: General , 1718471717735> at zombie.core.logger.ZipLogs.addDirToZipLua(ZipLogs.java:264).
[15-06-24 19:15:17.736] ERROR: General , 1718471717736> at zombie.core.logger.ZipLogs.addZipFile(ZipLogs.java:80).
[15-06-24 19:15:17.736] ERROR: General , 1718471717736> at zombie.network.CoopMaster.readServer(CoopMaster.java:243).
[15-06-24 19:15:17.736] ERROR: General , 1718471717736> at java.base/java.lang.Thread.run(Unknown Source).

**Comment by ZioPao** [comment]
I'd need the logs for the server to help you, I'm not sure what could be wrong with only this information, sorry

**Comment by Baklazan-guy** [comment]
I have no idea if this is the right one but i think it is, its my first time doing things like finding the logs so sorry if im wrong


[15-06-24 19:15:17.734] ERROR: General     , 1718471717734> java.nio.file.NoSuchFileException: /lua/AshenMPRanking/servertest.
[15-06-24 19:15:17.735] ERROR: General     , 1718471717735> 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.deleteFile(Unknown Source).
[15-06-24 19:15:17.735] ERROR: General     , 1718471717735> 	at jdk.zipfs/jdk.nio.zipfs.ZipPath.delete(Unknown Source).
[15-06-24 19:15:17.735] ERROR: General     , 1718471717735> 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.delete(Unknown Source).
[15-06-24 19:15:17.735] ERROR: General     , 1718471717735> 	at java.base/java.nio.file.Files.delete(Unknown Source).
[15-06-24 19:15:17.735] ERROR: General     , 1718471717735> 	at zombie.core.logger.ZipLogs.deleteDirectory(ZipLogs.java:305).
[15-06-24 19:15:17.735] ERROR: General     , 1718471717735> 	at zombie.core.logger.ZipLogs.addDirToZipLua(ZipLogs.java:264).
[15-06-24 19:15:17.736] ERROR: General     , 1718471717736> 	at zombie.core.logger.ZipLogs.addZipFile(ZipLogs.java:80).
[15-06-24 19:15:17.736] ERROR: General     , 1718471717736> 	at zombie.network.CoopMaster.readServer(CoopMaster.java:243).
[15-06-24 19:15:17.736] ERROR: General     , 1718471717736> 	at java.base/java.lang.Thread.run(Unknown Source).

**Comment by Baklazan-guy** [comment]
> I'd need the logs for the server to help you, I'm not sure what could be wrong with only this information, sorry

i edited the comment but im not sure if i got the thing that you meant

**Comment by ZioPao** [comment]
That's unrelated to this mod. Sorry but I can't help you. You should ask on the official Discord server for the game
